### ISSUE TITLE
荣耀V10拔掉数据线几分钟后，软件自动变成了未激活状态。

### ISSUE THREAD

**Issue by kouzhaokui** [Septillion/KFMARK#14]
如题

**Comment by Septillion** [comment]
可能是系统后台限制较严格。请告知系统版本。

**Comment by kouzhaokui** [comment]
> 可能是系统后台限制较严格。请告知系统版本。

版本号为：BKL-AL20 8.0.0.203(c00gt)

**Comment by sherlock2221b** [comment]
同版本，问题一样，且只需要5s左右就会变成未激活状态，历史纪录偶尔会弹出读取失败

**Comment by Septillion** [comment]
Duplicate of #23 同是荣耀手机
