### ISSUE TITLE
请支持主流Linux发行版

### ISSUE THREAD

**Issue by yincolor** [Septillion/KFMARK#24]
比如Ubuntu、manjaro，我看lib里边都是Jar包，应该能移植到GNU/Linux上。

**Comment by Septillion** [comment]
目前 Windows 版还不完善，Mac 版还没开发，所以 Linux 版 PC 助手的优先级可能不会太高。其实部署 daemon 只有三行 adb 命令，我相信大部分 Linux 用户都很熟悉 Terminal，可以敲命令激活。

**Comment by Flyfish233** [comment]
没有必要，主流发行版可以安装 ADB 工具包，或者使用 Google 已编译的
