### ISSUE TITLE
/system/bin/sh: ./daemon: not executable: 64-bit ELF file

### ISSUE THREAD

**Issue by longshishui** [Septillion/KFMARK#33]
![snipaste_2018-11-12_19-43-49](https://user-images.githubusercontent.com/25874746/48345557-4e2e6d00-e6b3-11e8-9241-cd44395b06ca.png)

![image](https://user-images.githubusercontent.com/25874746/48346009-a9149400-e6b4-11e8-983f-bd40568c9a0d.png)

**Comment by Septillion** [comment]
不支持 32 位设备
