### ISSUE TITLE
测试应用卸载后停止录制显示绝地求生

### ISSUE THREAD

**Issue by hbbxmjbb** [Septillion/KFMARK#43]
Device Model: Xiaomi Mi Mix 2S
Device Android Version:9
Device ROM Version:MIUI10 8.11.14
---
Bug Description:测试应用卸载后停止录制显示绝地求生
--
Steps to Reproduce:开始录制，卸载测试应用，停止录制，历史记录显示绝地求生，数据不显示。

**Comment by Septillion** [comment]
Duplicate of #13
