### ISSUE TITLE
华为畅玩7S帧率显示和记录都保持在0fps

### ISSUE THREAD

**Issue by 371dsdxr** [Septillion/KFMARK#48]
**Describe the bug**
HUAWEI enjoy 7S mobile phone(FIG-AL10) running in any game and application, KFMARK frame rate display and record are maintained at 0fps.
**To Reproduce**
1. Go to 'KFMark'
2. Click on '运行'
3. look the top of the mobile phone,and click on "开始记录"
4.When the game and the KFMARK APP running after a while,click on"停止记录",and click on "是"

**Expected behavior**
You will see the fps was 0 in the average of"平均FPS".

**Screenshots**
![Uploading Screenshot_20181117-223844.jpg…]()
![Uploading Screenshot_20181117-223941.jpg…]()

**Smartphone (please complete the following information):**
 - Device: HUAWEI enjoy 7S(FIG-AL10)
 - OS: EMUI8.0(Bulit on Android 8.0)
 - Browser :Via
 - Version 3.4.2

**描述bug *
华为畅享7S在任何游戏和应用中运行（FIG-AL10），快否帧率显示和记录均保持在0FPS。
**重现过程**
1.打开快否
2.点击“运行”
3.观察手机的顶部，点击“开始记录”
4.游戏和快否应用程序运行一段时间后，点击“停止记录”，点击“是”
**预期行为**
你会在平均FPS的框里看到FPS的平均值为0。
***截图**
已在上面
**智能手机：**
设备：华为畅享7S（FIG-AL10）
系统:EMUI8.0（Android 8上的BLIT）
浏览器：Via
3.4.2版

**Comment by Septillion** [comment]
Duplicate of #17
