### ISSUE TITLE
刺激战场封号

### ISSUE THREAD

**Issue by BaiSheng10081** [Septillion/KFMARK#50]
**封号问题**
+ 在测试刺激战场之际，约莫二十分钟，游戏弹出封号的警示语，说客服端文件不正常，故封号10分钟，请问这个问题可以修复吗？
+ 并没有开启Xposed、外挂程序
+ 机型为红米note5

**Comment by BaiSheng10081** [comment]
> **封号问题**
> 
> * 在测试刺激战场之际，约莫二十分钟，游戏弹出封号的警示语，说客服端文件不正常，故封号10分钟，请问这个问题可以修复吗？
> * 并没有开启Xposed、外挂程序
> * 机型为红米note5

**Comment by Septillion** [comment]
腾讯不会对测试软件做封号处理，应该是你自己的外挂修改了游戏文件。

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: BaiSheng <notifications@github.com>
发送时间: 星期日, 十一月 18, 2018 22:57
收件人: Septillion/KFMARK
抄送: Subscribed
主题: Re: [Septillion/KFMARK] 刺激战场封号 (#50)


封号问题

  *   在测试刺激战场之际，约莫二十分钟，游戏弹出封号的警示语，说客服端文件不正常，故封号10分钟，请问这个问题可以修复吗？
  *   并没有开启Xposed、外挂程序
  *   机型为红米note5

―
